name = "denver-social-hub"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "denver-social"
database_id = "402f83a5-8907-4666-8343-7d12e90ef9c3"

[assets]
binding = "ASSETS"
directory = "./dist/client"
